import {missing,text,get,list,number,money,date,dateKey,document as doc,yesNo,code,parseInput,prioritySort,addressSort,updated,redact} from './cadastral-format.js';
const $=id=>document.getElementById(id), tabs=['personal','contacts','addresses','financial','technical'];
let source=null,reveal=false,activeTab='personal';
function el(tag,content,cls){const n=document.createElement(tag);if(content!==undefined)n.textContent=content;if(cls)n.className=cls;return n;}
function button(label,action,cls='btn btn-outline'){const b=el('button',label,cls);b.type='button';b.addEventListener('click',action);return b;}
function state(id){for(const name of ['stateEmpty','stateProcessing','stateError','dashboard'])$(name).classList.toggle('hidden',name!==id);$('stateAnnouncement').textContent=id==='stateProcessing'?'Processando dados':id==='stateError'?'Não foi possível carregar a consulta':id==='dashboard'?'Consulta carregada':'';}
function changeTab(id,focus=false){activeTab=id;for(const p of tabs){const on=p===id;$('tab-'+p).classList.toggle('active',on);$('tab-'+p).setAttribute('aria-selected',on);$('tab-'+p).tabIndex=on?0:-1;$('panel-'+p).classList.toggle('active',on);$('panel-'+p).hidden=!on;}if(focus)$('tab-'+id).focus();}
function privateText(v){return missing(v)?'Não informado':reveal?text(v):'••••••';}
function grid(fields){const dl=el('dl',undefined,'field-grid');for(const [label,value] of fields){const item=el('div',undefined,'field');item.append(el('dt',label),el('dd',text(value)));dl.append(item);}return dl;}
function badge(value){const s=text(value),key=s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const kind={'otimo':'green','bom':'blue','ruim':'orange','pessimo':'red','confirmado':'green','sem evidencia':'gray','invalido':'red'}[key]||'gray';return el('span',s,'source-badge '+kind);}
function table(title,items,columns){const section=el('section',undefined,'table-section');section.append(el('h3',title));if(!items.length){section.append(el('p','Nenhum registro retornado','empty-note'));return section;}const wrap=el('div',undefined,'table-scroll');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label',title);const t=el('table');const caption=el('caption',title,'sr-only');t.append(caption);const head=el('thead'),hr=el('tr');for(const [label]of columns){const th=el('th',label);th.scope='col';hr.append(th);}head.append(hr);t.append(head);const body=el('tbody');for(const row of items){const tr=el('tr');for(const [,fn]of columns){const td=el('td');const val=fn(row);if(val instanceof Node)td.append(val);else td.textContent=text(val);tr.append(td);}body.append(tr);}t.append(body);wrap.append(t);section.append(wrap);return section;}
function expand(title,value){const details=el('details',undefined,'technical-section');details.append(el('summary',title));if(missing(value)||Array.isArray(value)&&!value.length||value&&typeof value==='object'&&!Object.keys(value).length)details.append(el('p','Nenhum registro retornado'));else details.append(el('pre',JSON.stringify(reveal?value:redact(value),null,2)));return details;}
function render(){
 const r=get(source,'resultado')||{},d=get(r,'dados')||{},power=list(get(r,'poder_aquisitivo'))[0]??get(r,'poder_aquisitivo'),scores=list(get(r,'score','scores'))[0]||{};
 const readScore=(...keys)=>get(scores,...keys)??get(d,...keys)??get(r,...keys);
 const powerLabel=typeof power==='object'?get(power,'PODER_AQUISITIVO','DESCRICAO','CLASSIFICACAO'):power;
 const range=get(power,'FX_PODER_AQUISITIVO','FX_RENDA','FAIXA_RENDA','DESCRICAO_RENDA');
 const phones=list(get(r,'telefone','telefones')),emails=prioritySort(list(get(r,'email','emails'))),addresses=addressSort(list(get(r,'enderecos')));
 const success=get(source,'sucesso');const successYes=success===true||success===1||success==='true';const failed=success===false||success===0||success==='false';
 const header=$('consultationHeader');header.replaceChildren();const top=el('div',undefined,'consultation-heading'),identity=el('div');identity.append(el('p','Consulta cadastral','heading-context'),el('h2',text(get(d,'NOME','NOME_COMPLETO'))),el('p','CPF '+doc(get(d,'CPF'),'cpf',reveal),'identity-cpf'));const toggle=button(reveal?'Ocultar dados sensíveis':'Mostrar dados sensíveis',()=>{reveal=!reveal;render();$('privacyToggle').focus();});toggle.id='privacyToggle';toggle.setAttribute('aria-pressed',reveal);top.append(identity,toggle);header.append(top);
 const meta=el('div',undefined,'consultation-meta');meta.append(el('span',successYes?'Consulta concluída':failed?'Falha na consulta':'Status não informado','source-badge '+(successYes?'green':failed?'red':'gray')),el('span','Tipo de busca: '+text(get(source,'tipo_busca'))));const duration=number(get(source,'tempo_segundos'));meta.append(el('span','Tempo de resposta: '+(duration===null?'Não informado':duration.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+' s')));header.append(meta,el('p','O status indica o resultado da requisição. Os dados e as classificações são informações da fonte, sem validação em tempo real.','source-note'));
 if(failed)header.append(el('p','A API informou falha na consulta. Os campos eventualmente retornados estão disponíveis abaixo.','notice error'));
 if(!get(source,'resultado')||!get(r,'dados')||!Object.keys(d).length)header.append(el('p','Resultado ausente ou incompleto. Campos não retornados são exibidos como “Não informado”.','notice'));
 const summary=$('summaryCards');summary.replaceChildren();for(const [title,value,note,target]of [['Renda informada',reveal?money(get(d,'RENDA')):privateText(get(d,'RENDA')),text(powerLabel)],['Score informado',privateText(readScore('CSBA')),'Classificação da fonte: '+privateText(readScore('CSBA_FAIXA'))],['Telefones',phones.length,'Registros retornados','contacts'],['Endereços',addresses.length,'Registros retornados','addresses']]){const card=el('article',undefined,'summary-card');card.append(el('h3',title),el('strong',text(value)),el('p',title==='Renda informada'&&!reveal&&!missing(powerLabel)?'••••••':note));if(target)card.append(button(target==='contacts'?'Ver contatos →':'Ver endereços →',()=>changeTab(target,true),'summary-link'));summary.append(card);}
 $('panel-personal').replaceChildren(grid([
 ['Nome completo',text(get(d,'NOME','NOME_COMPLETO'))],['CPF',doc(get(d,'CPF'),'cpf',reveal)],['Data de nascimento',reveal?date(get(d,'NASC','NASCIMENTO','DATA_NASCIMENTO')):privateText(get(d,'NASC','NASCIMENTO','DATA_NASCIMENTO'))],['Sexo',code(get(d,'SEXO'))],['Nome da mãe',privateText(get(d,'NOME_MAE','MAE'))],['Nome do pai',privateText(get(d,'NOME_PAI','PAI'))],['RG',privateText(get(d,'RG'))],['Órgão emissor',text(get(d,'ORGAO_EMISSOR','ORGAO_RG'))],['UF do documento',text(get(d,'UF_EMISSAO','UF_RG','UF_EMISSOR'))],['Nacionalidade',code(get(d,'NACIONALID'))],['Estado civil',code(get(d,'ESTCIV'))],['PIS',privateText(get(d,'PIS')??list(get(r,'pis')).map(p=>get(p,'PIS')).filter(v=>!missing(v)).join(', '))],['Título de eleitor',privateText(get(d,'TITULO_ELEITOR'))]
 ]));
 $('panel-contacts').replaceChildren(el('p','Qualidade, status e tipo são indicadores originais da fonte. Não indicam validação atual nem disponibilidade de WhatsApp.','source-note'),table('Telefones',phones,[['Número',p=>{let n=get(p,'TELEFONE','NUMERO');const ddd=get(p,'DDD');if(!missing(ddd)&&!missing(n)&&String(n).replace(/\D/g,'').length<=9)n=String(ddd)+String(n);return doc(n,'phone',reveal);}],['Tipo na fonte',p=>text(get(p,'TIPO','TIPO_TELEFONE'))],['Classificação original',p=>text(get(p,'CLASSIFICACAO'))],['Inclusão',p=>date(get(p,'DT_INCLUSAO','DATA_INCLUSAO'))],['Informação',p=>date(get(p,'DT_INFORMACAO','DATA_INFORMACAO'))]]),table('E-mails',emails,[['Prioridade',p=>text(get(p,'PRIORIDADE'))],['E-mail',p=>privateText(get(p,'EMAIL','E_MAIL'))],['Qualidade na fonte',p=>badge(get(p,'EMAIL_SCORE','QUALIDADE'))],['Status na fonte',p=>badge(get(p,'STATUS_VT','EMAIL_STATUS','STATUS'))],['Pessoal',p=>yesNo(get(p,'EMAIL_PESSOAL','PESSOAL'))],['Duplicado',p=>yesNo(get(p,'EMAIL_DUPLICADO','DUPLICADO'))],['Inclusão',p=>date(get(p,'DT_INCLUSAO','DATA_INCLUSAO'))]]));
 const addressPanel=$('panel-addresses');addressPanel.replaceChildren(el('p','Registros da base, ordenados por atualização. A data mais recente não confirma residência atual.','source-note'));const cards=el('div',undefined,'address-grid');if(!addresses.length)cards.append(el('p','Nenhum registro retornado','empty-note'));const latest=dateKey(updated(addresses[0]));addresses.forEach((a,i)=>{const card=el('article',undefined,'address-card');card.append(el('h3',`Endereço ${i+1}`));if(latest&&dateKey(updated(a))===latest)card.append(el('span','Atualização mais recente na base','source-badge blue'));card.append(grid([['Logradouro',privateText(get(a,'LOGRADOURO','LOGR_NOME'))],['Tipo de logradouro',text(get(a,'LOGR_TIPO'))],['Número',privateText(get(a,'NUMERO','LOGR_NUMERO'))],['Complemento',privateText(get(a,'COMPLEMENTO','LOGR_COMPLEMENTO'))],['Bairro',privateText(get(a,'BAIRRO'))],['Cidade',privateText(get(a,'CIDADE','MUNICIPIO'))],['UF',text(get(a,'UF'))],['CEP',doc(get(a,'CEP'),'cep',reveal)],['Inclusão',date(get(a,'DT_INCLUSAO','DATA_INCLUSAO'))],['Atualização',date(updated(a))]]));cards.append(card);});addressPanel.append(cards);
 $('panel-financial').replaceChildren(el('p','Valores informados na base; não representam renda comprovada nem recomendação de crédito.','source-note'),grid([['Renda informada na base',reveal?money(get(d,'RENDA')):privateText(get(d,'RENDA'))],['Poder aquisitivo',privateText(powerLabel)],['Faixa de renda da fonte',privateText(range)],['Score CSBA',privateText(readScore('CSBA'))],['Classificação CSBA na fonte',privateText(readScore('CSBA_FAIXA'))],['Score CSB8',privateText(readScore('CSB8'))],['Classificação CSB8 na fonte',privateText(readScore('CSB8_FAIXA'))]]));
 const identifiers={},codes={},dates={};for(const [k,v]of Object.entries(d)){if(/(^ID|CONTATOS_ID|CADASTRO)/i.test(k))identifiers[k]=v;else if(/COD|CBO|MOSAIC|ESTCIV|NACIONALID|SEXO/i.test(k))codes[k]=v;else if(/DT_|DATA|SITUACAO/i.test(k))dates[k]=v;}
 const metaData=Object.fromEntries(Object.entries(source).filter(([k])=>k.toLowerCase()!=='resultado'));
 $('panel-technical').replaceChildren(el('p',reveal?'Dados sensíveis visíveis.':'Valores ocultos por padrão, inclusive no JSON. Use “Mostrar dados sensíveis” para revelar.','source-note'),expand('Identificadores de contato e cadastro',identifiers),expand('Códigos de classificação',codes),expand('Datas de informação e situação cadastral',dates),expand('Metadados da requisição',metaData),expand('Demais campos do resultado',r),expand('TSE',get(r,'tse')),expand('Parentes',get(r,'parentes')),expand('JSON formatado — campos originais',source));changeTab(activeTab);
}
$('tabsNav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)changeTab(b.dataset.tab);});
$('tabsNav').addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.indexOf(activeTab);const next=e.key==='Home'?0:e.key==='End'?4:(i+(e.key==='ArrowRight'?1:4))%5;changeTab(tabs[next],true);});
$('inputToggle').addEventListener('click',()=>{const expanded=$('inputToggle').getAttribute('aria-expanded')!=='true';$('inputToggle').setAttribute('aria-expanded',expanded);$('inputBody').classList.toggle('hidden',!expanded);$('chevron').textContent=expanded?'▾':'▸';});
$('btnClear').addEventListener('click',()=>{source=null;reveal=false;activeTab='personal';$('jsonInput').value='';for(const p of tabs)$('panel-'+p).replaceChildren();$('consultationHeader').replaceChildren();$('summaryCards').replaceChildren();state('stateEmpty');$('jsonInput').focus();});
$('btnVisualize').addEventListener('click',async()=>{const input=$('jsonInput').value;$('btnVisualize').disabled=true;$('btnClear').disabled=true;state('stateProcessing');await new Promise(resolve=>setTimeout(resolve,30));try{source=parseInput(input);reveal=false;activeTab='personal';render();$('jsonInput').value='';state('dashboard');}catch(error){source=null;$('errorTitle').textContent=error instanceof SyntaxError?'JSON inválido':'Resposta não reconhecida';$('errorMessage').textContent=error instanceof SyntaxError?'Confira as aspas, vírgulas e chaves. Aceitamos JSON puro ou o prefixo “api desenvolvida por @astrahvhdev telegram”.':error.message;state('stateError');}finally{$('btnVisualize').disabled=false;$('btnClear').disabled=false;}});
